import turtle
bob = turtle.Turtle()
lives = 4
points = 0



def Belgium():
    s = turtle.Screen()
    s.bgcolor("white")
    bob.fillcolor("Black")
    bob.penup()
    bob.goto(-150, 0)
    bob.pendown()
    bob.begin_fill()
    bob.forward(60)
    bob.left(90)
    bob.forward(150)
    bob.left(90)
    bob.forward(60)
    bob.left(90)
    bob.forward(150)
    bob.left(90)
    bob.end_fill()
    bob.penup()
    bob.forward(60)
    bob.fillcolor("yellow")
    bob.pendown()
    bob.begin_fill()
    bob.forward(60)
    bob.left(90)
    bob.forward(150)
    bob.left(90)
    bob.forward(60)
    bob.left(90)
    bob.forward(150)
    bob.left(90)
    bob.end_fill()
    bob.penup()
    bob.forward(60)
    bob.fillcolor("red")
    bob.pendown()
    bob.begin_fill()
    bob.forward(60)
    bob.left(90)
    bob.forward(150)
    bob.left(90)
    bob.forward(60)
    bob.left(90)
    bob.forward(150)
    bob.left(90)
    bob.end_fill()

def Ireland():
    s = turtle.Screen()
    s.bgcolor("white")
    bob.fillcolor("orange")
    bob.penup()
    bob.goto(-150, 0)
    bob.pendown()
    bob.begin_fill()
    bob.forward(60)
    bob.left(90)
    bob.forward(150)
    bob.left(90)
    bob.forward(60)
    bob.left(90)
    bob.forward(150)
    bob.left(90)
    bob.end_fill()
    bob.penup()
    bob.forward(60)
    bob.fillcolor("white")
    bob.pendown()
    bob.begin_fill()
    bob.forward(60)
    bob.left(90)
    bob.forward(150)
    bob.left(90)
    bob.forward(60)
    bob.left(90)
    bob.forward(150)
    bob.left(90)
    bob.end_fill()
    bob.penup()
    bob.forward(60)
    bob.fillcolor("green")
    bob.pendown()
    bob.begin_fill()
    bob.forward(60)
    bob.left(90)
    bob.forward(150)
    bob.left(90)
    bob.forward(60)
    bob.left(90)
    bob.forward(150)
    bob.left(90)
    bob.end_fill()

def Romania():
    s = turtle.Screen()
    s.bgcolor("white")
    bob.fillcolor("blue")
    bob.penup()
    bob.goto(-150, 0)
    bob.pendown()
    bob.begin_fill()
    bob.forward(60)
    bob.left(90)
    bob.forward(150)
    bob.left(90)
    bob.forward(60)
    bob.left(90)
    bob.forward(150)
    bob.left(90)
    bob.end_fill()
    bob.penup()
    bob.forward(60)
    bob.fillcolor("yellow")
    bob.pendown()
    bob.begin_fill()
    bob.forward(60)
    bob.left(90)
    bob.forward(150)
    bob.left(90)
    bob.forward(60)
    bob.left(90)
    bob.forward(150)
    bob.left(90)
    bob.end_fill()
    bob.penup()
    bob.forward(60)
    bob.fillcolor("red")
    bob.pendown()
    bob.begin_fill()
    bob.forward(60)
    bob.left(90)
    bob.forward(150)
    bob.left(90)
    bob.forward(60)
    bob.left(90)
    bob.forward(150)
    bob.left(90)
    bob.end_fill()

def Nigeria():
    s = turtle.Screen()
    s.bgcolor("white")
    bob.fillcolor("green")
    bob.penup()
    bob.goto(-150, 0)
    bob.pendown()
    bob.begin_fill()
    bob.forward(60)
    bob.left(90)
    bob.forward(150)
    bob.left(90)
    bob.forward(60)
    bob.left(90)
    bob.forward(150)
    bob.left(90)
    bob.end_fill()
    bob.penup()
    bob.forward(60)
    bob.fillcolor("white")
    bob.pendown()
    bob.begin_fill()
    bob.forward(60)
    bob.left(90)
    bob.forward(150)
    bob.left(90)
    bob.forward(60)
    bob.left(90)
    bob.forward(150)
    bob.left(90)
    bob.end_fill()
    bob.penup()
    bob.forward(60)
    bob.fillcolor("green")
    bob.pendown()
    bob.begin_fill()
    bob.forward(60)
    bob.left(90)
    bob.forward(150)
    bob.left(90)
    bob.forward(60)
    bob.left(90)
    bob.forward(150)
    bob.left(90)
    bob.end_fill()

def Mali():
    s = turtle.Screen()
    s.bgcolor("white")
    bob.fillcolor("green")
    bob.penup()
    bob.goto(-150, 0)
    bob.pendown()
    bob.begin_fill()
    bob.forward(60)
    bob.left(90)
    bob.forward(150)
    bob.left(90)
    bob.forward(60)
    bob.left(90)
    bob.forward(150)
    bob.left(90)
    bob.end_fill()
    bob.penup()
    bob.forward(60)
    bob.fillcolor("gold")
    bob.pendown()
    bob.begin_fill()
    bob.forward(60)
    bob.left(90)
    bob.forward(150)
    bob.left(90)
    bob.forward(60)
    bob.left(90)
    bob.forward(150)
    bob.left(90)
    bob.end_fill()
    bob.penup()
    bob.forward(60)
    bob.fillcolor("red")
    bob.pendown()
    bob.begin_fill()
    bob.forward(60)
    bob.left(90)
    bob.forward(150)
    bob.left(90)
    bob.forward(60)
    bob.left(90)
    bob.forward(150)
    bob.left(90)
    bob.end_fill()

def France():
    s = turtle.Screen()
    s.bgcolor("white")
    bob.fillcolor("blue")
    bob.penup()
    bob.goto(-150, 0)
    bob.pendown()
    bob.begin_fill()
    bob.forward(60)
    bob.left(90)
    bob.forward(150)
    bob.left(90)
    bob.forward(60)
    bob.left(90)
    bob.forward(150)
    bob.left(90)
    bob.end_fill()
    bob.penup()
    bob.forward(60)
    bob.fillcolor("white")
    bob.pendown()
    bob.begin_fill()
    bob.forward(60)
    bob.left(90)
    bob.forward(150)
    bob.left(90)
    bob.forward(60)
    bob.left(90)
    bob.forward(150)
    bob.left(90)
    bob.end_fill()
    bob.penup()
    bob.forward(60)
    bob.fillcolor("red")
    bob.pendown()
    bob.begin_fill()
    bob.forward(60)
    bob.left(90)
    bob.forward(150)
    bob.left(90)
    bob.forward(60)
    bob.left(90)
    bob.forward(150)
    bob.left(90)
    bob.end_fill()

def Bangladesh():
    s = turtle.Screen()
    s.bgcolor("white")
    bob.fillcolor("dark green")
    bob.penup()
    bob.goto(-150, 0)
    bob.pendown()
    bob.begin_fill()
    bob.forward(200)
    bob.left(90)
    bob.forward(100)
    bob.left(90)
    bob.forward(200)
    bob.left(90)
    bob.forward(100)
    bob.end_fill()
    bob.penup()
    bob.goto(-77, 50)
    bob.fillcolor("red")
    bob.pendown()
    bob.begin_fill()
    bob.circle(30)
    bob.end_fill()

def Cameroon():
    s = turtle.Screen()
    s.bgcolor("white")
    bob.fillcolor("dark green")
    bob.penup()
    bob.goto(-150, 0)
    bob.pendown()
    bob.begin_fill()
    bob.forward(60)
    bob.left(90)
    bob.forward(150)
    bob.left(90)
    bob.forward(60)
    bob.left(90)
    bob.forward(150)
    bob.left(90)
    bob.end_fill()
    bob.penup()
    bob.forward(60)
    bob.fillcolor("red")
    bob.pendown()
    bob.begin_fill()
    bob.forward(60)
    bob.left(90)
    bob.forward(150)
    bob.left(90)
    bob.forward(60)
    bob.left(90)
    bob.forward(150)
    bob.left(90)
    bob.end_fill()
    bob.penup()
    bob.forward(60)
    bob.fillcolor("yellow")
    bob.pendown()
    bob.begin_fill()
    bob.forward(60)
    bob.left(90)
    bob.forward(150)
    bob.left(90)
    bob.forward(60)
    bob.left(90)
    bob.forward(150)
    bob.left(90)
    bob.end_fill()
    bob.penup()
    bob.goto(-60, 68)
    bob.fillcolor("yellow")
    bob.pendown()
    bob.begin_fill()
    bob.circle(5)
    bob.end_fill()
import random



countries = [ Belgium , Ireland , Romania , Nigeria , Mali , France , Bangladesh , Cameroon]
while lives > 0 and len(countries) > 0:
    bob.reset()
    flag = random.choice(countries)
    flag()


    answer = input("Guess the flag ?: ")

    if answer == flag.__name__:
        print("You are right")
        points = points + 1
        print("You have:", points,"pointes")
        print("You have:", lives, "lives")
        countries.remove(flag)
    else:
        print("You are wrong")
        lives = lives - 1
        print("you have:", points,"points")
        print("you have:", lives,"lives")
        countries.remove(flag)
if points >8:
    print("Your score: <<Good>>")
elif points >5:
    print("Your score: <<Average>>")
else:
    print("Your score: <<Bad>> ")
turtle.done()